<a href="https://colab.research.google.com/github/yeshwanth098/sml/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Salary_Data.csv')
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
y=df['Salary']
print(y)
print(y.shape)

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64
(30,)

In [ ]:
x=df['YearsExperience']
print(x)
print(x.shape)

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64
(30,)

In [ ]:
xx=(x-xmin())/(x.max()-x.min())
print(xx)

In [ ]:
yy=(y-y.min())/(y.max()-y.min())
print(yy

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(x,y)
plt.xlabel('YearsExperience')
plt.ylabel('Salary')
plt.title('Salary vs Experience')
plt.show()

In [ ]:
import pandas as pd
df = pd.read_csv('/content/diabetes_data_upload.csv')
df

In [ ]:
m=df['class']
print(m)

In [ ]:
n=df.drop('class',axis=1)
print(n)

In [ ]:
import pandas as pd
for col in n.columns:
  if n[col].dtype == 'object':
try:
      n[col] = pd.to_numeric(n[col], errors='coerce')
    except:
        print(f"Could not convert column {col} to numeric. It might contain non-numerical values.")
        n = n.fillna(0)
        pp=(n-n.min())/(n.max()-n.min())
        print(pp)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 6)

In [ ]:
 import matplotlib.pyplot as plt
 plt.plot(n,m)
 plt.xlabel('x- axis')
 plt.ylabel('y- axis')
 plt.title('Diabetis')
 plt.show()

NameError: name 'n' is not defined